Sprint 3/step 1
Irek84/CosmoBurgers pull request #5
Opened 2022-05-28 21:31 UTC by Irek84

2022-05-29 07:59 UTC, grishbar reviewed
Большая работа проделана, весь запрашиваемый функционал реализован, правильно воспользовался react router, круто что из стора всегда селектишь только нужные тебе значения. Видно, что стараешься соблюдать единый стиль написания кода, как написал в одном из комментариев, можешь поставить себе eslint, он поможет тебе следить за стилем кода еще более качественно. Есть несколько моментов, которые нужно поправить до принятия работы:

- [ ] Для неавторизированных пользователей кнопка “оформить заказ” должна вести на страницу авторизации (/login) c редиректор обратно после успешной авторизации
- [ ] Обрати внимание, на то как должна выглядеть страница с деталями ингредиента, это должна быть полноценная страница, а не только юрл
- [ ] Даже после авторизации и обновлении страницы, кнопка “оформить заказ” не работает
- [ ] Исправить начальное состояние “Личный кабиент” для уже авторизованных пользователей
- [ ] Избавиться от ненужного кода
- [ ] Удалить ненужные комментарии
- [ ] Перенести логику авторизации, и обновления токенов в reducer и actions
- [ ] Также обрати внимание на ошибки в консоли при старте твоего приложения, от всех них нужно избавиться

Удачи в рефакторинге!)

2022-05-29 07:59 UTC, grishbar commented on src/components/app/app.jsx
> +//    const background = location.state && location.state.background;
`можно лучше`
    комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2022-05-29 07:59 UTC, grishbar commented on src/components/protected-route/protected-route.jsx
> +        dispatch(updateTokenEnhancer());
`надо исправить` 
нужно перенести логику авторизирован пользователь или нет, и все с этим связанное в редьюсеры и экшены. При загрузке приложения один раз проверять авторизацию, токены, и сеттить нужное состояние. А дальше во всех компонентах где понадобится проверять авторизацию, брать все из хранилища. Иначе у тебя будет появляться дублирование кода и некоторые компоненты будут делать одно и то же

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +	const [values, setValues] = useState({});
`можно лучше` 
это спорный вопрос как делать лучше, но я всегда за то, чтобы по дэфолту, в переменных хранящее состояние компонента ставить falsy значение, если нет никаких данных. Это поможет легко определить ставили мы какое то значение в стейт или нет. То есть тут хотелось бы увидеть null, а не пустой объект

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +	}, [userData, setIsUseOldValues, setValues]);
`надо исправить` 
кажется этот блок кода лишний можно все сделать без него

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +	}
`можно лучше` 
для всех этих функций можно заиспользовать [useCallback](https://ru.reactjs.org/docs/hooks-reference.html#usecallback) это поможет оптимизировать приложение

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +		setIsFormChange(false);
`надо исправить` 
после сабмита принято очищать форму, если все прошло успешно

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +				onChange={(e) => handleChange(e)}
`надо исправить`
    [нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html). Также не забудь исправить и в других местах этот момент

2022-05-29 07:59 UTC, grishbar commented on src/components/user-profile/user-profile.jsx
> +				</Button>
`можно лучше`
обычно принято писать вот так:
```
<Button
	type="primary"
	size="medium"
	name="save"
>
	Сохранить
</Button>
```
 можешь установить и настроить eslint для этого запусти вот эту команду 
    `npm i eslint-config-airbnb eslint-plugin-jsx-a11y --save-dev`
    далее надо создать файлик `.eslintrc` в корне проекта и туда записать:
```
    {
        "extends": [
          "react-app",
          "airbnb",
          "plugin:jsx-a11y/recommended"
        ],
        "plugins": [
          "jsx-a11y"
        ],
        "rules": {
          "semi": 0,
          "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", "tsx"] }]
        }
    }
```
    после этих действий у тебя в коде будет везде подсвечиваться некорректный синтаксис, сможешь легко привести проект к единому стилю, правда текущую проблему он не подсветит для этого понадобится еще добавить [соответствующий плагин ](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md)

2022-05-29 07:59 UTC, grishbar commented on src/pages/forgot-password.jsx
> +    const isAccessTokenExist = document.cookie.indexOf('accessToken=') !== -1;
`надо исправить` 
не забудь и тут убрать, когда перенесешь логику в редьюсер

2022-05-29 07:59 UTC, grishbar commented on src/pages/forgot-password.jsx
> +    }
`можно лучше` 
тоже отличное место для useCallback

2022-05-29 07:59 UTC, grishbar commented on src/pages/forgot-password.jsx
> +        :
`надо исправить` 
нужно сделать универсальный компонент ProtectedRoute, а не дублировать эту логику в каждом компоненте, согласно пункту *6. Защищённые маршруты в приложении* задания. Подумай, как это можно сделать

2022-05-29 07:59 UTC, grishbar commented on src/pages/main.jsx
> +}
`можно лучше`
```
const ErrorContent = () => (
  <div className={`${styles.error} text text_type_main-medium`}>
    Произошла ошибка
  </div>
)

const AppLoadingContent = () => (
  <div className={`${styles.notification} text text_type_main-medium`}>
    Загрузка...
  </div>
)

const MainContent = () => (
  <DndProvider
    backend={HTML5Backend}
  >
    <BurgerIngredients />
    <BurgerConstructor />
  </DndProvider> 
);

...
  if (isLoading) {
    return <AppLoadingContent />
  }

  if (hasError) {
    return <ErrorContent />;
  }

  return (
    <main>
      <MainContent />
      {isModalVisible && (
        <Modal
          title={modalTitle}
          onClose={closeModal}
        >
          {modalContent}
        </Modal>
      )} 
    </main>
  );
```
Это субъективно, но я стараюсь придерживаться мнения, что любой блок кода, который атомарен и не зависит от других частей функции, надо выносить в отдельную функцию, потому что в таком случае читать код становится напорядок легче. Также тогда каждую эту функцию ты сможешь задокументировать при помощи [JSDOC](https://jsdoc.app/about-getting-started.html)  разработчики гугла рекомендует каждую функцию так документировать

2022-05-29 07:59 UTC, grishbar commented on src/services/actions/user.js
> +				});
`надо исправить` 
тут тоже надо в err что то положить либо саму ошибку либо res.msg, тут зависит от проекта, но скорей всего у тебя запрос успешно выполнился но вернулся к примеру с ошибкой 403, что у пользователя нет прав, и тут как договоритесь с бэкендом, вероятней всего в поле msg он будет класть ответ, что пошло не так и ты должен будешь уметь его показать, поэтому тут бы тоже сохранить куда нибудь объект результата запроса

2022-05-29 07:59 UTC, grishbar commented on src/services/actions/user.js
> +				setCookie('accessToken', res.accessToken);
`надо исправить` 
либо все храни в куках, либо все храни в localstorage, довольно странно часть аутентификационной информации хранить в одном месте а другую часть в другом

2022-05-30 15:22 UTC, grishbar requested changes
Отлично, работа стала напорядок лучше осталось еще немножко недочетов и приму работу:

- [x] Все еще не сделал страничку с деталями ингредиента, так как сказано в задании
- [x] После успешного оформления заказа, состояние конструктора должно сбрасываться
- [x] Перенести всю логику аутентификации пользователя в экшен

2022-05-30 15:22 UTC, grishbar commented on src/components/app/app.jsx
> +    }, [dispatch, isAccessTokenExist, isRefreshTokenExist]);
`надо исправить` 
Хотелось бы, чтобы это был action который взаимодействует со твоим стором, и в app.jsx ты один раз вызываешь useEffect, который вызывает этот экшен на проверку аутентифицирован пользователь или нет, есть токены нет, нужно но ли рефрешнуть токены и так далее.
Нет каких то супер понятных аргументов, почему должно быть именно так, единственное, что могу привести, это, что хранить логику аутентфикации в app.jsx как то странновато, тут должен только вызываться метод который всю эту логику содержит, так как аутентификация это отдельный смысловой блок и его вполне можно вынести, а если и выносить, то кажется, что он должен быть в экшенах

2022-05-30 15:22 UTC, grishbar commented on src/components/ingredient-details/ingredient-details.jsx
> +	let { id } = useParams();
`надо исправить` 
кажется это должно быть const

2022-05-30 20:04 UTC, grishbar approved these changes
Отлично, теперь все великолепно, классно, что ты прикрутил eslint и поправил все стилевые ошибки 👍  Удачи в дальнейшем обучении)

2022-05-30 20:04 UTC, grishbar commented on src/components/app/app.jsx
> +            }
`можно лучше` 
```
            redirectСondition={
              isAuthenthicated || (!setNewPasswordFailed && setNewPasswordMessage) ||
                  !resetPasswordMessage
            }
```

2022-05-30 20:11 UTC, Irek84 commented on src/components/app/app.jsx
> +            }
> Отлично, теперь все великолепно, классно, что ты прикрутил eslint и поправил все стилевые ошибки 👍 Удачи в дальнейшем обучении)

Спасибо за ревью! Благодаря твоим советам мой код стал лучше) ✌️

2022-05-30 20:24 UTC, merged